CREATE DATABASE foreverly;

CREATE USER foreverly WITH CREATEDB PASSWORD 'forever';

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO foreverly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE          ON SEQUENCES TO foreverly;

CREATE TABLE "user" (
    user_id serial PRIMARY KEY,
    username VARCHAR (50) UNIQUE NOT NULL,
    password VARCHAR (73) NOT NULL,
    email VARCHAR (355) UNIQUE NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    last_login TIMESTAMP
);

